language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: HyUEIz7ma/hbwFh8cdPhscPPdFUXgNSPPqmBMkaQrYfmXDNaAy6PbPbKPZ4BAuzKvbHIpV7Grl8p8DuLhskHVn5eumxQ+0eix+h0G1duymoZPjNx+mD/EHvdVnHNPtlGIq9rBPKUIr48fEj0PW+xI/6yQCjEKZWZM/mhqL1bQMDNYV/Y//5eYwiNRFqbpBkQG2LQgOaMzavLuq8kycXBBI/STT+/n9u9Z2ApBvZzan+f1LIFv+MjzRtGsTdeHYWf7NW/jeeZ0TVVL65QuaxVMQJgo98cKX8wLzHcLLNslhAij8kxA/P9VwIWCRPzNZy+IMW9yTC3SAb+vmoP+XhJdI5F61lxcHOYK5um/6/3bE8+paW9ZF0u8RQTssPZ1wXPgINCXeZxSwlKmaJ72/2/bKFH21ZcdoIK27l++p3iNcYWUIpZMU6ksJlW3YNr5kfKM70MI2YbFt4MgAxYCE82YCjE1MbrF9vpRqfBoxqYKlurqXrtHGyFsbN4dJClduehNKRBfhY/3eMpP6BWN5d6yJHUQGD8UQJbhnmAItMX8idmw0+L3DpUFxNOkJZpHxAD/Ck0ZwDoCa7t0dEhhswdOpVg3VjHAGooqicJ0CybKuVLmFi9mrgXhSft01BDLOD18lMggL+hK76DOeIGz8qaKMBeIIV+c/3Hp/QpHGL5aAc=
  app: vaneatsandtreats
  on:
    branch: master
    repo: donaldma/vaneatsandtreats
  run:
  - knex migrate:latest
  - knex seed:run
